### ISSUE TITLE
Provide query filters for /apis and /tenants endpoints

### ISSUE THREAD

**Issue by mdeuser** [openwhisk/apigateway#56]
Would like to have ability to filter the returned data.  Syntax in the following proposed examples is not final, but conveys the kind of filtering being requested.

`GET /tenants?namespace=NAMESPACE`
`GET /tenants?namespace=NAMESPACE&instance=INSTANCE`
`GET /tenants/TENANTID/apis?basePath=BASEPATH`
`GET /tenants/TENANTID/apis?name=NAME`

**Comment by alexsong93** [comment]
@mdeuser Some questions:

- for `/tenants/TENANTID/apis?basePath=BASEPATH`, should the return value be a list, or just one API object instead of a list, since there could only be one basePath for a given tenant?  
- same question for `/tenants/TENANTID/apis?name=NAME` - should it return just one object? Or can there be multiple APIs with the same name?
- Are there any other fields that you would like to filter on?
- Do you want the filters for the `/apis` endpoint as well (e.g. `/apis?basePath=BASEPTH`)?

**Comment by alexsong93** [comment]
@mdeuser do you want the syntax to be how you have it above, or match the syntax of the ys1/prod gateway? (eg. `/tenants?filter[where][namespace]=NAMESPACE`)

**Comment by mdeuser** [comment]
@alexsong93 I currently have code that uses the Strongloop query filter syntax, but should be easily changeable to another query filter syntax.  At one point, @lostinthestory mentioned not wanting to follow the Strongloop syntax.

**Comment by lostinthestory** [comment]
@mdeuser I think so long as we're using the loopback syntax filter in the online case, we should match between both cases.

**Comment by mdeuser** [comment]
@lostinthestory - That works for me.  Thanks.
